18-349 Lab 4: pwm_driver.c File Reference
pwm_driver.c File Reference
LKM driver for the RPi motor pwm.
#include <linux/init.h>
#include <linux/module.h>
#include <linux/device.h>
#include <linux/kernel.h>
#include <linux/fs.h>
#include <asm/uaccess.h>
#include <linux/io.h>
#include <linux/gpio.h>
#include <linux/interrupt.h>
#include <linux/hrtimer.h>
#include <linux/ktime.h>
Macros
#define gpioPWM 12
the pwm pin number
#define NAME "motor_pwm"
the name of the device
Functions
MODULE_LICENSE ("GPL")
Module info: license.
MODULE_AUTHOR ("LASTONE")
Module info: author(s)
MODULE_DESCRIPTION ("A simple Linux motor driver for the RPi motor")
Module info: description.
MODULE_VERSION ("0.1")
Module info: version.
static int driver_open (struct inode *inodep, struct file *filep)
The device open function that is called each time the device is opened This will only increment the numberOpens counter in this case.
static int driver_release (struct inode *inodep, struct file *filep)
The device release function that is called whenever the device is closed/released by the userspace program.
static ssize_t driver_read (struct file *filep, char *buffer, size_t len, loff_t *offset)
This function is called whenever device is being read from user space.
static ssize_t driver_write (struct file *filep, const char *buffer, size_t len, loff_t *offset)
This function is called whenever the device is being written to from user space.
enum hrtimer_restart my_hrtimer_callback (struct hrtimer *timer)
this function iscalled when a hr timer reaches 0
static int __init pwm_init (void)
Called when the module is loaded with insmod.
static void __exit pwm_exit (void)
Called when the module is unloaded with rmmod.
static int parseInt (const char *s, int len)
This function parses an interger from the input char.
module_init (pwm_init)
Registering the module init function with the kernel.
module_exit (pwm_exit)
Registering the module exit function with the kernel.
Variables
static struct hrtimer hr_timer
the hr timer struct
static ktime_t ktime
the ktime struct
unsigned long timer_interval_ns = 1e6
time interval
static unsigned long off
time interval for off
static unsigned long on
time interval for duty cycle on
static int major_number
device major number
static int cycle = 0
number of cycles
static bool onOrOff = false
on/off indicator of duty cycle
static struct class * this_class = NULL
class struct pointer
static struct device * this_device = NULL
device struct pointer
static struct file_operations fops
The file operations structure lists the callback functions that you can associate with the file operations.
Detailed Description
LKM driver for the RPi motor pwm.
Author
David Dong haoch.nosp@m.end@.nosp@m.andre.nosp@m.w.cm.nosp@m.u.edu
Function Documentation
static int driver_open (struct inode * inodep, struct file * filep) static
The device open function that is called each time the device is opened This will only increment the numberOpens counter in this case.
Parameters
inodep A pointer to an inode object (defined in linux/fs.h)
filep A pointer to a file object (defined in linux/fs.h)
static ssize_t driver_read (struct file * filep, char * buffer, size_t len, loff_t * offset) static
This function is called whenever device is being read from user space.
Parameters
filep A pointer to a file object (defined in linux/fs.h)
buffer The pointer to the buffer to which this function writes the data
len The length of the b
offset The offset if required
static int driver_release (struct inode * inodep, struct file * filep) static
The device release function that is called whenever the device is closed/released by the userspace program.
Parameters
inodep A pointer to an inode object (defined in linux/fs.h)
filep A pointer to a file object (defined in linux/fs.h)
static ssize_t driver_write (struct file * filep, const char * buffer, size_t len, loff_t * offset) static
This function is called whenever the device is being written to from user space.
Parameters
filep A pointer to a file object
buffer The buffer to that contains the string to write to the device
len The length of the array of data that is being passed in the const char buffer
offset The offset if required
References cycle, hr_timer, ktime, my_hrtimer_callback(), off, on, onOrOff, parseInt(), and timer_interval_ns.
module_exit (pwm_exit)
Registering the module exit function with the kernel.
direction_exit: The function that holds the module's exit routine
module_init (pwm_init)
Registering the module init function with the kernel.
direction_init: The function that holds the module's init routine
enum hrtimer_restart my_hrtimer_callback (struct hrtimer * timer)
this function iscalled when a hr timer reaches 0
Parameters
timer is the hrtimer that is currently used
References gpioPWM, off, on, and onOrOff.
Referenced by driver_write(), and pwm_init().
static int parseInt (const char * s, int len) static
This function parses an interger from the input char.
Parameters
s the string
len the length of desired number
Referenced by driver_write().
static int __init pwm_init (void) static
Called when the module is loaded with insmod.
Returns
0 on failure or a non-zero value on success
References fops, gpioPWM, hr_timer, ktime, major_number, my_hrtimer_callback(), NAME, this_class, this_device, and timer_interval_ns.
Variable Documentation
struct file_operations fops static
Initial value:
={
  .open = driver_open,
  .read = driver_read,
  .write = driver_write,
  .release = driver_release,
}
The file operations structure lists the callback functions that you can associate with the file operations.
Referenced by pwm_init().