18-349 Lab 4: wheel_encoder_driver.c File Reference
wheel_encoder_driver.c File Reference
LKM driver for the RPi wheel enccoder.
#include <linux/init.h>
#include <linux/module.h>
#include <linux/device.h>
#include <linux/kernel.h>
#include <linux/fs.h>
#include <asm/uaccess.h>
#include <linux/io.h>
#include <linux/gpio.h>
#include <linux/interrupt.h>
Macros
#define NAME "wheel_encoder"
define the name of the device
#define LED_RED_PIN 35
GPIO pin number for red led.
#define MOTOR1 21
GPIO pin number for motor 1.
#define MOTOR2 20
GPIO pin number for motor 2.
#define BUTTON 26
GPIO pin number for down button.
#define ENC0A 6
GPIO pin number for encoder0 channel A.
#define ENC0B 7
GPIO pin number for encoder0 channel B.
#define ENC1A 17
GPIO pin number for encoder1 channel A.
#define ENC1B 23
GPIO pin number for encoder1 channel B.
#define TIMER_INTERVAL 1e9
timer interval
#define WHEEL_COUNTER 1200
wheel steps
#define FULLROUND 360
full round degree num
Functions
MODULE_LICENSE ("GPL")
Module info: license.
MODULE_AUTHOR ("LASTONE")
Module info: author(s)
MODULE_DESCRIPTION ("A simple Linux motor driver for the RPi motor")
Module info: description.
MODULE_VERSION ("0.1")
Module info: version.
static int my_driver_open (struct inode *inodep, struct file *filep)
The device open function that is called each time the device is opened.
static int my_driver_release (struct inode *inodep, struct file *filep)
The device release function that is called whenever the device is closed/released by the userspace program.
static ssize_t my_driver_read (struct file *filep, char *buffer, size_t len, loff_t *offset)
This function is called whenever device is being read from user space i.e. data is being sent from the device to the user.
static irq_handler_t enc_irq_handler (unsigned int irq, void *dev_id, struct pt_regs *regs)
Function prototype for the custom IRQ handler function – see below for the implementation.
enum hrtimer_restart my_hrtimer_callback (struct hrtimer *timer)
the hr timer callback function that is called when the timer gets finished.
static int __init motor_driver_init (void)
Called when the module is loaded with insmod.
static void __exit motor_driver_exit (void)
Called when the module is unloaded with rmmod.
module_init (motor_driver_init)
Registering the module init function with the kernel.
module_exit (motor_driver_exit)
Registering the module exit function with the kernel.
Variables
static struct file_operations fops
Devices are represented as file structure in the kernel.
static int majorNumber
major number of the device
static int irqEncNumberA
irq number of enc channel A
static int irqEncNumberB
irq number of enc channel B
static struct device * device = NULL
the device driver device struct pointer
static int dir
direction of the wheel
static int angle
angle count
static int count
step counts within the current sec
static int speed
current speed
static struct hrtimer hr_timer
hr timer
static ktime_t ktime
ktime struct
static char output [64] = {0}
buffer for read output
Detailed Description
LKM driver for the RPi wheel enccoder.
Author
David Dong haoch.nosp@m.end@.nosp@m.andre.nosp@m.w.cm.nosp@m.u.edu Yanying Zhu yanyi.nosp@m.ngz@.nosp@m.andre.nosp@m.w.cm.nosp@m.u.edu
Function Documentation
static irq_handler_t enc_irq_handler (unsigned int irq, void * dev_id, struct pt_regs * regs) static
Function prototype for the custom IRQ handler function – see below for the implementation.
The GPIO IRQ Handler function that happens on a step within the encoder.
Parameters
irq the IRQ number that is associated with the GPIO – useful for logging.
dev_id the *dev_id that is provided – can be used to identify which device caused the interrupt Not used in this example as NULL is passed.
regs h/w specific register values – only really ever used for debugging. return returns IRQ_HANDLED if successful – should return IRQ_NONE otherwise.
References angle, count, dir, ENC0A, ENC0B, irqEncNumberA, irqEncNumberB, and WHEEL_COUNTER.
Referenced by motor_driver_init().
module_exit (motor_driver_exit)
Registering the module exit function with the kernel.
LED_driver_exit: The function that holds the module's exit routine
module_init (motor_driver_init)
Registering the module init function with the kernel.
LED_driver_init: The function that holds the module's init routine
static int __init motor_driver_init (void) static
Called when the module is loaded with insmod.
Returns
0 on failure or a non-zero value on success
References device, ENC0A, ENC0B, enc_irq_handler(), fops, hr_timer, irqEncNumberA, irqEncNumberB, ktime, majorNumber, my_hrtimer_callback(), NAME, and TIMER_INTERVAL.
static int my_driver_open (struct inode * inodep, struct file * filep) static
The device open function that is called each time the device is opened.
Parameters
inodep A pointer to an inode object (defined in linux/fs.h)
filep A pointer to a file object (defined in linux/fs.h)
static ssize_t my_driver_read (struct file * filep, char * buffer, size_t len, loff_t * offset) static
This function is called whenever device is being read from user space i.e. data is being sent from the device to the user.
Parameters
filep A pointer to a file object (defined in linux/fs.h)
buffer The pointer to the buffer to which this function writes the data
len The length of the b
offset The offset if required
References angle, FULLROUND, output, and WHEEL_COUNTER.
static int my_driver_release (struct inode * inodep, struct file * filep) static
The device release function that is called whenever the device is closed/released by the userspace program.
Parameters
inodep A pointer to an inode object (defined in linux/fs.h)
filep A pointer to a file object (defined in linux/fs.h)
enum hrtimer_restart my_hrtimer_callback (struct hrtimer * timer)
the hr timer callback function that is called when the timer gets finished.
Parameters
timer is the hr timer struct that is used
Returns
a macro
References count, dir, speed, and TIMER_INTERVAL.
Referenced by motor_driver_init().
Variable Documentation
struct file_operations fops static
Initial value:
=
{
  .open = my_driver_open,
  .read = my_driver_read,
  .release = my_driver_release,
}
Devices are represented as file structure in the kernel.
Referenced by motor_driver_init().